import type { Track } from "./types";

export const tracks: Track[] = [
  {
    src: "/tracks/ostinato altered.wav",
    title: "Study - Ostinato Altered - Inception",
    artist: "Diego Blattner",
    duration: 77.575333,
    type: "audio",
  },
  {
    src: "/tracks/Decipio lure the guard.wav",
    title: "Decipio - lure the guard",
    artist: "Diego Blattner",
    duration: 23.684218,
    type: "audio",
  },
  {
    src: "/tracks/Decipio boss office.wav",
    title: "Decipio - Boss' Office",
    artist: "Diego Blattner",
    duration: 42,
    type: "audio",
  },
  {
    src: "/tracks/Decipio assassin smuggled.wav",
    title: "Decipio - Assassin Smuggled",
    artist: "Diego Blattner",
    duration: 24.971293,
    type: "audio",
  },
  {
    src: "/tracks/Decipio ending.wav",
    title: "Decipio - Ending",
    artist: "Diego Blattner",
    duration: 40.678798,
    type: "audio",
  },
  {
    src: "/tracks/lonely planet.wav",
    title: "Lonely Planet",
    artist: "Diego Blattner",
    duration: 152.727292,
    type: "audio",
  },
  {
    src: "/tracks/pirates.wav",
    title: "Study over dialogue - Pirates",
    artist: "Diego Blattner",
    duration: 74.4,
    type: "audio",
  },
  {
    src: "/videos/monument valey.mp4",
    title: "Monument Valey - trailer study",
    artist: "Diego Blattner",
    duration: 45.263167,
    type: "video",
  },
  {
    src: "/tracks/the last of us.wav",
    title: "The Last of Us - Chase scene",
    artist: "Diego Blattner",
    duration: 184,
    type: "audio",
  },
  {
    src: "/tracks/noir.wav",
    title: "Noir",
    artist: "Diego Blattner",
    duration: 35.675687,
    type: "audio",
  },
  {
    src: "/tracks/journey.wav",
    title: "Journey - Miraak's rebirth",
    artist: "Diego Blattner",
    duration: 350.98625,
    type: "audio",
  },
  {
    src: "/tracks/field his hers tog.wav",
    title: "Field, His, Hers, Together",
    artist: "Diego Blattner",
    duration: 16.695668,
    type: "audio",
  },
  {
    src: "/tracks/diatonic substitution.wav",
    title: "Study - Diatonic Substitution",
    artist: "Diego Blattner",
    duration: 77.064229,
    type: "audio",
  },
  {
    src: "/tracks/bob white devil.wav",
    title: "Bob the White Devil",
    artist: "Diego Blattner",
    duration: 21.132789,
    type: "audio",
  },
  {
    src: "/tracks/Down the stairs.wav",
    title: "Down the Stairs",
    artist: "Diego Blattner",
    duration: 47.012063,
    type: "audio",
  },
  {
    src: "/tracks/fun.wav",
    title: "Fun",
    artist: "Diego Blattner",
    duration: 14.189208,
    type: "audio",
  },
  {
    src: "/tracks/lead the way.wav",
    title: "Lead the Way",
    artist: "Diego Blattner",
    duration: 53.333333,
    type: "audio",
  },
  {
    src: "/tracks/melos.wav",
    title: "Study - Melos",
    artist: "Diego Blattner",
    duration: 32.876734,
    type: "audio",
  },
  {
    src: "/tracks/racing skyhigh.wav",
    title: "Racing Skyhigh",
    artist: "Diego Blattner",
    duration: 121.551746,
    type: "audio",
  },
];
