import type { Track } from "./types";

export const tracks: Track[] = [
  {
    src: "/tracks/ostinato altered.wav",
    title: "Study - Ostinato Altered - Inception",
    artist: "Diego Blattner",
    duration: 77.575333,
    type: "audio",
  },
  {
    src: "/tracks/Decipio - lure the guard.mp3",
    title: "Decipio - lure the guard",
    artist: "Diego Blattner",
    duration: 21.289775,
    type: "audio",
  },
  {
    src: "/tracks/Decipio - boss office.mp3",
    title: "Decipio - Boss' Office",
    artist: "Diego Blattner",
    duration: 38.060375,
    type: "audio",
  },
  {
    src: "/tracks/Decipio - assassin smuggled.mp3",
    title: "Decipio - Assassin Smuggled",
    artist: "Diego Blattner",
    duration: 21.86445,
    type: "audio",
  },
  {
    src: "/tracks/Decipio - ending.mp3",
    title: "Decipio - Ending",
    artist: "Diego Blattner",
    duration: 36.2318,
    type: "audio",
  },
  {
    src: "/tracks/lonely planet.mp3",
    title: "Lonely Planet",
    artist: "Diego Blattner",
    duration: 152.737925,
    type: "audio",
  },
  {
    src: "/tracks/pirates.wav",
    title: "Study over dialogue - Pirates",
    artist: "Diego Blattner",
    duration: 74.4,
    type: "audio",
  },
  {
    src: "/videos/monument valey.mp4",
    title: "Monument Valey - trailer study",
    artist: "Diego Blattner",
    duration: 45.312,
    type: "video",
  },
  {
    src: "/tracks/the last of us.wav",
    title: "The Last of Us - Chase scene",
    artist: "Diego Blattner",
    duration: 184,
    type: "audio",
  },
  {
    src: "/tracks/noir.wav",
    title: "Noir",
    artist: "Diego Blattner",
    duration: 35.675687,
    type: "audio",
  },
  {
    src: "/tracks/journey.mp3",
    title: "Journey - Miraak's rebirth",
    artist: "Diego Blattner",
    duration: 348.49955,
    type: "audio",
  },
  {
    src: "/tracks/field his hers tog.mp3",
    title: "Field, His, Hers, Together",
    artist: "Diego Blattner",
    duration: 16.6922,
    type: "audio",
  },
  {
    src: "/tracks/diatonic substitution.mp3",
    title: "Study - Diatonic Substitution",
    artist: "Diego Blattner",
    duration: 74.004875,
    type: "audio",
  },
  {
    src: "/tracks/bob white devil.mp3",
    title: "Bob the White Devil",
    artist: "Diego Blattner",
    duration: 12.0163,
    type: "audio",
  },
  {
    src: "/tracks/Down the stairs.wav",
    title: "Down the Stairs",
    artist: "Diego Blattner",
    duration: 47.012063,
    type: "audio",
  },
  {
    src: "/tracks/fun.mp3",
    title: "Fun",
    artist: "Diego Blattner",
    duration: 13.087325,
    type: "audio",
  },
  {
    src: "/tracks/lead the way.mp3",
    title: "Lead the Way",
    artist: "Diego Blattner",
    duration: 53.342,
    type: "audio",
  },
  {
    src: "/tracks/melos.mp3",
    title: "Study - Melos",
    artist: "Diego Blattner",
    duration: 31.999975,
    type: "audio",
  },
  {
    src: "/tracks/racing skyhigh.mp3",
    title: "Racing Skyhigh",
    artist: "Diego Blattner",
    duration: 40.515875,
    type: "audio",
  },
];
